name: Translate README

on:
  push:
    paths:
      - 'README.md'

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Run translation program
      run: |
        chmod +x ./tools/Pozdrav  # Dovoli izvrševanje programa
        ./tools/Pozdrav           # Zaženi prevedeno aplikacijo za Linux

    - name: Commit translated files
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add *
        git commit -m "Automated translation of README.md"
        git push



    
