name: Pozdrav

on:
  push:
    paths:
      - 'README.md'  # Sproži akcijo ob spremembi README.md

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Uporabi različico .NET Core, ki ustreza tvojemu prevajalskemu programu

    - name: Install dependencies
      run: dotnet restore  # Če tvoj projekt uporablja NuGet pakete, jih bo to obnovilo

    - name: Run translation program
      run: |
        # Tu lahko prilagodiš klic svojega prevajalskega programa
        # Predpostavljamo, da imaš C# aplikacijo, ki prevaja README.md
        dotnet run --project D:/Challenger/testhooks/Pozdrav/Pozdrav/obj/Debug/net8.0/Pozdrav.exe

   
